export const INIT_FETCH_MOVIEWREVIEW = "INIT_FETCH_MOVIEREVIEW"
export const FETCH_MOVIEREVIEW_SUCESS = "FETCH_MOVIEREVIEW_SUCESS"
export const FETCH_MOVIEREVIEW_FAILED = "FETCH_MOVIEREVIEW_FAILED"

export const INIT_ADD_MOVIEWREVIEW = "INIT_ADD_MOVIEREVIEW"
export const ADD_MOVIEREVIEW_SUCESS = "ADD_MOVIEREVIEW_SUCESS"
export const ADD_MOVIEREVIEW_FAILED = "ADD_MOVIEREVIEW_FAILED"