export const INIT_FETCH_USER = "INIT_FETCH_USER"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILED = "FETCH_USER_FAILED"

export const INIT_ADD_USER = "INIT_ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILED = "ADD_USER_FAILED"

export const INIT_UPDATE_USER = "INIT_UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"

export const INIT_DELETE_USER = "INIT_DELETE_USER"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"

export const INIT_SINGLE_USER = "INIT_SINGLE_USER"
export const SINGLE_USER_SUCCESS = "SINGLE_USER_SUCCESS"
export const SINGLE_USER_FAILED = "SINGLE_USER_FAILED"