export const INIT_FETCH_BOOKINGS = "INIT_FETCH_BOOKINGS";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAILED = "FETCH_BOOKINGS_FAILED";

export const INIT_ADD_BOOKINGS = "INIT_ADD_BOOKINGS";
export const ADD_BOOKINGS_SUCCESS = "ADD_BOOKINGS_SUCCESS";
export const ADD_BOOKINGS_FAILED = "ADD_BOOKINGS_FAILED";

export const INIT_FETCH_MBOOKINGS = "INIT_FETCH_MBOOKINGS";
export const FETCH_MBOOKINGS_SUCCESS = "FETCH_MBOOKINGS_SUCCESS";
export const FETCH_MBOOKINGS_FAILED = "FETCH_MBOOKINGS_FAILED";
